version: 2.1
jobs:
  compile:
   docker:
      - image: panchajanya1999/archlinux:latest
   steps:
      - run:
          command: |
            pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio git python zip
            git clone --depth=1 https://github.com/missgoin/mojito.git -b main builder_kernel
            cd builder_kernel
            bash .circleci/mojito.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
